db:
  image: neo4j
  environment:
    - NEO4J_AUTH=none
    - NEO4J_ALLOW_STORE_UPGRADE=true
  volumes:
    - ./data:/data
  ports:
    - "7474:7474"

redis:
  image: redis
  ports:
    - "6379:6379"

web:
  build: .
  command: bundle exec rails s
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
    - redis
  stdin_open: true
  tty: true
