# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://localhost:6379/1

development:
  #adapter: async
  adapter: redis
  #url: redis://localhost:6379/1
  url: redis://<%= ENV['REDIS_PORT_6379_TCP_ADDR'] ||= ENV['DOCKER_HOST'].split('//')[1].split(':')[0] %>:<%= ENV['REDIS_PORT_6379_TCP_PORT'] ||= '6379' %>

#test:
#  adapter: async
